module.exports ={
    //Home
    INIT_THEME_DATA:'INIT_THEME_DATA',
    // address
    GET_CONDO_LIST: 'GET_CONDO_LIST',
    GET_CONDO_FUZZY: 'GET_CONDO_FUZZY',
    CHECK_CAN_DELIVER: 'CHECK_CAN_DELIVER',

    // product
    GET_SINGLE_PRODUCT: 'GET_SINGLE_PRODUCT',
    GET_HOME_DATA: 'GET_HOME_DATA',
    SEARCH_THEME_LIST: 'SEARCH_THEME_LIST',
    SEARCH_CATEGORY_LIST: 'SEARCH_CATEGORY_LIST',
    GET_CATEGORY_LIST: 'GET_CATEGORY_LIST',
    CHANGE_SELECT_ATTR: 'CHANGE_SELECT_ATTR',
    ADD_QUANTITY: 'ADD_QUANTITY',
    SUB_QUANTITY: 'SUB_QUANTITY',
    CHANG_PRODUCT_IMAGE: 'CHANG_PRODUCT_IMAGE',
    UPDATE_CART_TOTAL_QUANTITY: 'UPDATE_CART_TOTAL_QUANTITY',
    GET_PRODUCT_LISTS:'GET_PRODUCT_LISTS',

    // Manage
    GET_DAILY_REDIS: 'GET_DAILY_REDIS',

    // Order
    GET_ORDER_BEFORE: 'GET_ORDER_BEFORE',
    SBOX_CHECKOUT: 'SBOX_CHECKOUT',

    // User
    GET_ORDER_HISTORY: 'GET_ORDER_HISTORY',
    PUT_USER_ADDR: 'PUT_USER_ADDR',
    UPDATE_USER_AUTH: 'UPDATE_USER_AUTH',
    CLEAR_USER_AUTH: 'CLEAR_USER_AUTH',

    //cart
    UPDATE_CART_ITEM_QUANTITY: 'UPDATE_CART_ITEM_QUANTITY',

    GET_HISTORY_LIST: 'GET_HISTORY_LIST',
    CHECK_STOCK: 'CHECK_STOCK',
    CHECKOUT: 'CHECKOUT',
    CHECKOUT_FAIL: 'CHECKOUT_FAIL',

    SET_OUT_OF_STOCK: 'SET_OUT_OF_STOCK',

    //Sbox Category
    ADD_SEARCH_KEYWORD: 'ADD_SEARCH_KEYWORD',
    INIT_SEARCH_KEYWORD: 'INIT_SEARCH_KEYWORD',
    GET_SEARCH_KEYWORD: 'GET_SEARCH_KEYWORD',

    GET_PRODUCT_LIST: 'GET_PRODUCT_LIST',
    SBOX_VERSION: '2.5.10',

    //Test
    GET_SECOND_MENU_DATA: 'GET_SECOND_MENU_DATA',
    UPDATE_SECTION_LIST: 'UPDATE_SECTION_LIST',
};
